version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: /.github/scripts
    schedule:
      interval: weekly
    groups:
      pip:
        patterns: ['*']
  - package-ecosystem: github-actions
    directories: ['/', '/.github/actions/*']
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
