name = "ciphermaniac-daily-pricing-cron"
compatibility_date = "2023-10-30"

# Cron Trigger to run daily at 20:30 UTC (3:30 PM CST)
triggers = { crons = [ "30 20 * * *" ] }

# Optional: set a default site URL if you want to override via env variables
[vars]
SITE_URL = "https://ciphermaniac.com/api/daily-pricing"
 
main = "index.js"
