export const elements = {
  page: document.querySelector('.archetype-page') as HTMLElement | null,
  loading: document.getElementById('archetype-loading'),
  error: document.getElementById('archetype-error'),
  simple: document.querySelector('.archetype-simple') as HTMLElement | null,
  title: document.getElementById('archetype-title'),
  tabHome: document.getElementById('tab-home') as HTMLAnchorElement | null,
  tabAnalysis: document.getElementById('tab-analysis') as HTMLAnchorElement | null,
  tabTrends: document.getElementById('tab-trends') as HTMLAnchorElement | null,
  performanceFilter: document.getElementById('trends-performance-filter') as HTMLSelectElement | null,
  metaInfo: document.getElementById('trends-meta-info') as HTMLElement | null,
  statsSection: document.getElementById('trends-stats') as HTMLElement | null,
  statWeeks: document.getElementById('stat-weeks'),
  statTournaments: document.getElementById('stat-tournaments'),
  statCards: document.getElementById('stat-cards'),
  statRange: document.getElementById('stat-range'),
  narrativeSection: document.getElementById('trends-narrative') as HTMLElement | null,
  narrativeText: document.getElementById('narrative-text') as HTMLElement | null,
  insightsSection: document.getElementById('trends-insights') as HTMLElement | null,
  coreCount: document.getElementById('core-count'),
  coreList: document.getElementById('core-list'),
  flexCount: document.getElementById('flex-count'),
  flexList: document.getElementById('flex-list'),
  risingCount: document.getElementById('rising-count'),
  risingList: document.getElementById('rising-list'),
  fallingCount: document.getElementById('falling-count'),
  fallingList: document.getElementById('falling-list'),
  substitutionsSection: document.getElementById('trends-substitutions') as HTMLElement | null,
  substitutionsList: document.getElementById('substitutions-list'),
  matchupsSection: document.getElementById('trends-matchups') as HTMLElement | null,
  matchupsList: document.getElementById('matchups-body'),
  matchupsToggle: document.getElementById('matchups-toggle') as HTMLButtonElement | null,
  chartContainer: document.getElementById('trends-chart') as HTMLElement | null,
  chart: document.getElementById('trend-chart'),
  chartSubtitle: document.getElementById('chart-subtitle'),
  chartLegend: document.getElementById('chart-legend'),
  copyEvolutionSection: document.getElementById('copy-evolution') as HTMLElement | null,
  copyCardSelect: document.getElementById('copy-card-select') as HTMLSelectElement | null,
  copyChart: document.getElementById('copy-chart'),
  copyStats: document.getElementById('copy-stats') as HTMLElement | null,
  copyAvgCurrent: document.getElementById('copy-avg-current'),
  copyModeCurrent: document.getElementById('copy-mode-current'),
  copyChange: document.getElementById('copy-change'),
  toggleWeekly: document.getElementById('chart-toggle-weekly'),
  toggleDaily: document.getElementById('chart-toggle-daily'),
  chartSummary: document.getElementById('chart-summary'),
  summaryCardsCount: document.getElementById('summary-cards-count'),
  summaryAvgPlayrate: document.getElementById('summary-avg-playrate'),
  summaryPeak: document.getElementById('summary-peak'),
  summaryTrend: document.getElementById('summary-trend'),
  cardListSection: document.getElementById('trends-card-list'),
  cardSortSelect: document.getElementById('card-sort') as HTMLSelectElement | null,
  cardListBody: document.getElementById('card-list-body'),
  emptyState: document.getElementById('trends-empty')
};
