/**
 * Head-to-head matchup data: per-tournament matchup profiles, the online
 * archetype trends payload they fall back to, and the raw per-match records the
 * player and archetype pages join against.
 *
 * The match record readers keep their OWN session-lifetime caches rather than
 * relying on the transport's short TTL: a player page joins the same
 * multi-megabyte playerMatches.json across many interactions, and re-downloading
 * it every five minutes for a file that changes once a day is the wrong trade.
 * @module src/lib/data/matchups
 */

import { dataClient } from './client';
import { tournamentPath } from './paths';
import type { PlayerMatchRecord } from '../../types';

const { fetchJsonOptional } = dataClient;

// 'phaseWeighted' is no longer generated (the frontend only ever read
// qualityWeighted with fallback to 'all'), but it's kept in the union so old
// matchupProfiles.json files that still have it continue to parse.
type MatchupWeighting = 'all' | 'phaseWeighted' | 'qualityWeighted';

/**
 * One archetype-vs-archetype cell from `matchupProfiles.json`. `archetypeA`/`archetypeB`
 * are display labels (e.g. "Dragapult Dusknoir"), sorted alphabetically, so a given
 * archetype can appear on either side. Ties are folded into `winsA`/`winsB` as 0.5
 * each (so for a pair with no double-losses, `winsA + winsB === matches`). Recover the
 * raw record with `rawWinsA = winsA - ties/2`. `doubleLosses` count toward `matches`
 * but toward neither side's wins.
 */
export interface MatchupPair {
  archetypeA: string;
  archetypeB: string;
  matches: number;
  winsA: number;
  winsB: number;
  ties: number;
  doubleLosses: number;
  weightedWinsA: number;
  weightedWinsB: number;
  weightedTies: number;
  weightedWinRateA: number;
  weightedWinRateB: number;
  weightedMatches: number;
}

export interface MatchupProfile {
  name: MatchupWeighting;
  matchesConsidered: number;
  weightedMatches: number;
  byArchetypePair: MatchupPair[];
}

export interface MatchupProfilesPayload {
  generatedAt: string;
  tournament: { id: string; labsCode?: string; name: string; players: number; division?: string };
  phaseMultipliers: Record<string, number>;
  qualityModel: Record<string, unknown>;
  // Partial: new files omit 'phaseWeighted'; old files may still have it.
  profiles: Partial<Record<MatchupWeighting, MatchupProfile>>;
}

/**
 * Pre-aggregated archetype-vs-archetype matrix for a single event. Generated by
 * `aggregate_matchups()` in `.github/scripts/download-tournament.py` and stored at
 * `{tournament}/matchupProfiles.json`. Present for major events only; returns null
 * for the online meta, snapshots, and any scope without the file so callers degrade
 * gracefully (use `fetchArchetypeMatchupsOnline` for the online scope).
 */
export function fetchMatchupProfiles(tournament: string): Promise<MatchupProfilesPayload | null> {
  return fetchJsonOptional<MatchupProfilesPayload>(`${tournamentPath(tournament)}/matchupProfiles.json`);
}

/**
 * One opponent's head-to-head record as stored in the online meta. Unlike the
 * majors file, `winRate` here is `wins / total` (ties excluded from the numerator,
 * included in the denominator) — recompute as `(wins + ties/2)/total` if you want
 * the ties-as-half convention the majors file uses.
 */
export interface OnlineMatchupRecord {
  opponent: string;
  wins: number;
  losses: number;
  ties: number;
  total: number;
  winRate: number;
}

interface ArchetypeTrendsPayload {
  matchups?: Record<string, OnlineMatchupRecord>;
}

/**
 * Online-meta matchups. The online pipeline doesn't emit `matchupProfiles.json`;
 * it embeds a `matchups` map (opponent label → record) inside each archetype's
 * `trends.json` (built by `generateArchetypeTrends` → `buildMatchupMatrix`). Returns
 * null if the archetype has no trends file or no matchups.
 */
export async function fetchArchetypeMatchupsOnline(
  tournament: string,
  archetypeBase: string
): Promise<Record<string, OnlineMatchupRecord> | null> {
  const trends = await fetchJsonOptional<ArchetypeTrendsPayload>(
    `${tournamentPath(tournament)}/archetypes/${encodeURIComponent(archetypeBase)}/trends.json`
  );
  return trends?.matchups ?? null;
}

/**
 * Every player's every round for one event (`playerMatches.json`). `playerId` is the
 * tournament-scoped id (= `tpId` in players.json, = the id in labs URLs), which joins
 * to `DeckRecord.playerId` (a string — coerce). Used by the card-impact analyzer.
 *
 * The file is ~7MB, so it's cached per tournament for the page session: the
 * dedupe in `fetchJson*` only holds entries for a short TTL, which would
 * re-download on each tool open without this cache.
 */
const playerMatchesCache = new Map<string, Promise<PlayerMatchRecord[] | null>>();

export function fetchPlayerMatches(tournament: string): Promise<PlayerMatchRecord[] | null> {
  const cached = playerMatchesCache.get(tournament);
  if (cached) {
    return cached;
  }
  const promise = fetchJsonOptional<PlayerMatchRecord[]>(`${tournamentPath(tournament)}/playerMatches.json`).catch(
    () => {
      // Don't pin a rejected promise — let a later open retry the download.
      playerMatchesCache.delete(tournament);
      return null;
    }
  );
  playerMatchesCache.set(tournament, promise);
  return promise;
}

/**
 * Per-archetype slice of `playerMatches.json`: only the round records whose pilot
 * belongs to `archetypeBase`, in the same {@link PlayerMatchRecord} shape. This is
 * what the card lens actually needs, and it's a few KB per deck instead of the
 * whole ~7MB event file. Returns null (404) for tournaments ingested before this
 * file existed — callers fall back to {@link fetchPlayerMatches}.
 */
const archetypeMatchesCache = new Map<string, Promise<PlayerMatchRecord[] | null>>();

export function fetchArchetypeMatches(tournament: string, archetypeBase: string): Promise<PlayerMatchRecord[] | null> {
  const cacheKey = `${tournament}::${archetypeBase}`;
  const cached = archetypeMatchesCache.get(cacheKey);
  if (cached) {
    return cached;
  }
  const promise = fetchJsonOptional<PlayerMatchRecord[]>(
    `${tournamentPath(tournament)}/archetypes/${encodeURIComponent(archetypeBase)}/matches.json`
  ).catch(() => {
    // Don't pin a rejected promise — let a later open retry the download.
    archetypeMatchesCache.delete(cacheKey);
    return null;
  });
  archetypeMatchesCache.set(cacheKey, promise);
  return promise;
}
